const weatherIcon = {
  1: require("../assets/images/weather/1.png"),
  2: require("../assets/images/weather/2.png"),
  3: require("../assets/images/weather/3.png"),
  4: require("../assets/images/weather/4.png"),
  5: require("../assets/images/weather/5.png"),
  6: require("../assets/images/weather/6.png"),
  7: require("../assets/images/weather/7.png"),
  8: require("../assets/images/weather/8.png"),
  9: require("../assets/images/weather/9.png"),
  10: require("../assets/images/weather/10.png"),
  11: require("../assets/images/weather/11.png"),
  12: require("../assets/images/weather/12.png"),
  13: require("../assets/images/weather/13.png"),
  14: require("../assets/images/weather/14.png"),
  15: require("../assets/images/weather/15.png"),
  16: require("../assets/images/weather/16.png"),
  17: require("../assets/images/weather/17.png"),
  18: require("../assets/images/weather/18.png"),
  19: require("../assets/images/weather/19.png"),
  20: require("../assets/images/weather/20.png"),
  21: require("../assets/images/weather/21.png"),
  22: require("../assets/images/weather/22.png"),
  23: require("../assets/images/weather/23.png"),
  24: require("../assets/images/weather/24.png"),
  25: require("../assets/images/weather/25.png"),
  26: require("../assets/images/weather/26.png"),
  27: require("../assets/images/weather/27.png"),
  28: require("../assets/images/weather/28.png"),
  29: require("../assets/images/weather/29.png"),
  30: require("../assets/images/weather/30.png"),
  31: require("../assets/images/weather/31.png"),
  32: require("../assets/images/weather/32.png"),
  33: require("../assets/images/weather/33.png"),
  34: require("../assets/images/weather/34.png"),
  35: require("../assets/images/weather/35.png"),
  36: require("../assets/images/weather/36.png"),
};

export default weatherIcon;
